components:
- components:
  - layout_properties: {grid_position: 'ZTPLQY,DNFCYD'}
    name: name_label
    properties: {align: center, content: name, font_size: 20}
    type: RichText
  - data_bindings: []
    layout_properties: {grid_position: 'TNEQVM,CIATQH'}
    name: image_content
    properties: {}
    type: Image
  - layout_properties: {grid_position: 'RVXVVZ,MVOTDG'}
    name: description_label
    properties: {align: center, content: description, font_size: 20}
    type: RichText
  - components:
    - data_bindings: []
      event_bindings: {click: add_button_click}
      layout_properties: {}
      name: add_button
      properties:
        background: theme:Primary
        bold: true
        font_size: 20
        role: filled-button
        text: |
          Add to Cart
        visible: true
      type: Button
    layout_properties: {grid_position: 'OIDYZE,PGUXTI'}
    name: button_label
    properties: {}
    type: RichText
  - layout_properties: {grid_position: 'OIDYZE,FGHIZF FKNDUB,ZIJJNP'}
    name: quantity_label
    properties:
      align: center
      text: |
        Number on Hand
    type: Label
  - layout_properties: {grid_position: 'OIDYZE,FGHIZF YJBJQE,ZSTRSI'}
    name: price_label
    properties: {align: center}
    type: Label
  layout_properties: {grid_position: 'CQNLFN,FGGXAK'}
  name: content_panel
  properties: {background: 'theme:Primary Container', border: '10px solid ', foreground: 'theme:Primary', role: elevated-card}
  type: ColumnPanel
container:
  properties: {role: null}
  type: ColumnPanel
custom_component: true
is_package: false
properties:
- {default_binding_prop: true, default_value: '', important: true, name: name, type: string}
- {important: true, name: image, type: object}
- {important: true, name: button_callback, type: object}
- {default_value: '', important: true, name: description, type: string}
- {important: true, name: button_text, type: object}
toolbox_item: {hidden: true}
