components:
- components:
  - layout_properties: {grid_position: 'ZTPLQY,DNFCYD'}
    name: name_label
    properties: {align: center, content: name, font_size: 20}
    type: RichText
  - data_bindings: []
    layout_properties: {grid_position: 'TNEQVM,CIATQH'}
    name: image_content
    properties: {}
    type: Image
  - layout_properties: {grid_position: 'RVXVVZ,MVOTDG'}
    name: description_label
    properties: {align: center, content: description, font_size: 20}
    type: RichText
  - data_bindings: []
    event_bindings: {click: button_click}
    layout_properties: {grid_position: 'ZAJMAG,KVBJLE'}
    name: button
    properties: {background: 'theme:Primary', font_size: 20, role: tonal-button, text: price, visible: true}
    type: Button
  layout_properties: {grid_position: 'CQNLFN,FGGXAK'}
  name: content_panel
  properties: {background: 'theme:Primary Container', border: '10px solid ', foreground: 'theme:Primary', role: elevated-card}
  type: ColumnPanel
- components: []
  layout_properties: {grid_position: 'APNJWM,CGTMUH'}
  name: column_panel_1
  properties: {}
  type: ColumnPanel
container:
  properties: {role: null}
  type: ColumnPanel
custom_component: true
is_package: false
properties:
- {default_binding_prop: true, default_value: '', important: true, name: name, type: string}
- {important: true, name: image, type: object}
- {default_value: '', important: true, name: description, type: string}
- {important: true, name: button_callback, type: object}
- {default_value: '', important: true, name: price, type: string}
- {default_value: '', important: true, name: quantity, type: string}
toolbox_item: {hidden: false, title: Products}
